108-top-header
cyder/cyder-website pull request #129
Opened 2017-06-18 13:06 UTC by rururuuko

topページのヘッダーを透過しました。

2017-06-18 13:18 UTC, mori-atsushi approved these changes

2017-06-18 13:18 UTC, Mori-Atsushi commented on css/top.css
> + }
文字色やロゴアイコンも変更お願いします！

2017-06-18 13:18 UTC, Mori-Atsushi commented on index.html
> +      <section id="top-content" class="top">
id指定消しましょう

2017-06-18 13:18 UTC, Mori-Atsushi commented on js/script.js
> +      var obj_t_pos = $('#main-content').offset().top; //位置設定
インデントがおかしい。

2017-06-18 13:18 UTC, Mori-Atsushi commented on js/script.js
> +        $('#main-header').removeClass();
removeClassの対象（'transparent'）を指定しておきましょうか。

2017-06-18 13:18 UTC, Mori-Atsushi commented on js/script.js
> +  $(window).scroll(function(){
スペース
```js
$(window).scroll(function() {
```

2017-06-18 13:18 UTC, Mori-Atsushi commented on js/script.js
> +      if(scr_count > obj_t_pos){
スペース
```js
if(scr_count > obj_t_pos) {
```

2017-06-18 13:18 UTC, Mori-Atsushi commented on js/script.js
> +      }else{
スペース
```js
} else {
```

2017-06-18 14:13 UTC, mori-atsushi requested changes
間違ってました。

2017-06-25 13:50 UTC, mori-atsushi reviewed
詳しくはあとで見ます。
@Nishihara-Daiki さんも確認お願いします。

2017-06-25 13:50 UTC, Mori-Atsushi commented on debug.log
> +[0619/225751.947:ERROR:process_info.cc(116)] ReadProcessMemory bool __cdecl crashpad::`anonymous-namespace'::ReadStruct<struct crashpad::process_types::PEB<struct crashpad::process_types::internal::T
余計なものがアップロードされてます。

2017-06-25 13:50 UTC, Mori-Atsushi commented on js/script.js
> +  $(window).scroll(function(){
治ってません。

2017-06-26 06:43 UTC, Nishihara-Daiki reviewed
@rururuuko @Mori-Atsushi 
+ 修正以外に相談事項もあります
+ 記法の統一、仕様の確認
@ehnh 
+ 画像のトリミングにも触れてます

2017-06-26 06:43 UTC, Nishihara-Daiki commented on css/top.css
> +   color:#ffffff;
スペース
```
color: #ffffff;
```

2017-06-26 06:43 UTC, Nishihara-Daiki commented on css/top.css
> +  background: url(../images/logo-white.png) no-repeat;
他のページも見ると、3種類が混ざってますね・・・ issue立てるレベル？
+ `background-image: url(path);`
+ `background-image: url("path");`
+ `background-image: url('path');`

2017-06-26 06:43 UTC, Nishihara-Daiki commented on js/script.js
> +      if(scr_count > obj_t_pos) {
`>=` の方がいいと思います

2017-06-26 06:43 UTC, Nishihara-Daiki commented on css/top.css
> +   background-color: transparent;
background-color: transparent;
background: transparent;
混在してますね、大した問題ではないですが

2017-06-26 06:43 UTC, Nishihara-Daiki commented on js/script.js
> +
画面ロード時にも `changeHeaderTranspearent()` を呼び出した方がいいかと思います

2017-06-26 06:43 UTC, Nishihara-Daiki commented on css/top.css
> +}
スタイル間に「改行を入れる」で統一しますか？

2017-06-26 06:43 UTC, Nishihara-Daiki commented on css/top.css
> +
ボタンだけアニメーションが付いてますが、どうしますか？
+ ボタンアニメーションを外す
```css
{
  transition: none;
  -webkit-transition: none;
}
```
+ ヘッダ全部にアニメーションをつける
```css
{
  transition: background-color 0.1s;
  ...
}
```
+ そのまま

2017-06-26 06:43 UTC, Nishihara-Daiki commented on css/top.css
> +  background: url(../images/logo-white.png) no-repeat;
画像をトリミングしたい
カラー版は、ぴったりサイズでトリミングされてるけど、白色透明版は、微妙に余白があるね
（画像にコメントできないとは・・

2017-06-26 06:43 UTC, Nishihara-Daiki commented on css/top.css
> +@media only screen and (min-width: 480px) {
ここに入ってる意図が読めませんでした
既存の後出の `@media only screen and (min-width: 480px) { ... }` に記述しても、動作に支障はないように見えますが・・・

2017-06-26 06:45 UTC, Mori-Atsushi commented on css/top.css
> +   background-color: transparent;
背景画像を消したいときは `background: transparent;` を使ってるはず…

2017-06-26 06:47 UTC, Mori-Atsushi commented on css/top.css
> +
* ヘッダ全部にアニメーションをつける
がベストだとは思うんだけど画像の切り替えだけは難しくてね…

2017-06-26 06:53 UTC, Nishihara-Daiki commented on css/top.css
> +   background-color: transparent;
transparent は background-color プロパティがとる値
background-image は url() か none をとる
という仕様だと思いますが、よろしいですか？

2017-06-26 06:56 UTC, Mori-Atsushi commented on css/top.css
> +   background-color: transparent;
たし蟹
backgroundで色指定してたので `background: transparent;` で統一しましょう

2017-06-26 06:56 UTC, Nishihara-Daiki commented on css/top.css
> +
切り替わり部分は背景の境界でもあるから、手元の動作確認では、背景色だけ変えても悪くはないとは思った

2017-06-26 06:59 UTC, Nishihara-Daiki commented on css/top.css
> +   background-color: transparent;
サイト全体で見れば、混ざってるんじゃないかな
そもそも、 `background-size` `background-position` を `background` から分けてる習慣も実はよく分からない・・・

2017-06-26 07:01 UTC, Mori-Atsushi commented on css/top.css
> +   background-color: transparent;
サイト全体でcssのリファクタリングが必要そう
とりあえずあんまり細かいとこまでは見ずに、気になったとこだけって感じで

2017-06-26 07:04 UTC, Mori-Atsushi commented on css/top.css
> +
少なくとも背景は必要そう
ボタンはメニューの開閉アニメーションの関係でtransitionがついてるんよね。allにしてるのが悪いんだけど。

2017-07-03 14:12 UTC, mori-atsushi requested changes
後もうちょっとです！

2017-07-03 14:12 UTC, Mori-Atsushi commented on css/top.css
> +}
謎スペースの変更が…！

2017-07-03 14:12 UTC, Mori-Atsushi commented on contact/index.html
> +      <h1><a href="../"><img src="../images/CyderLogo.png" alt="Cyder" class="title"></a></h1>
ファイル名はlogo.pngのままにしましょうか。

2017-07-03 14:12 UTC, Mori-Atsushi commented on debug.log
> +[0619/225751.947:ERROR:process_info.cc(116)] ReadProcessMemory bool __cdecl crashpad::`anonymous-namespace'::ReadStruct<struct crashpad::process_types::PEB<struct crashpad::process_types::internal::T
謎ファイルが消えていません。

2017-07-03 14:12 UTC, Mori-Atsushi commented on css/top.css
> +
以下のcssをheader内に追加をお願いします。

```css
header {
  transition: background-color 0.1s;
}
```

2017-07-09 11:05 UTC, mori-atsushi requested changes

2017-07-09 11:05 UTC, Mori-Atsushi commented on contact/index.html
> +      <h1><a href="../"><img src="../images/CyderLogo.png" alt="Cyder" class="title"></a></h1>
logo.pngに変えてください。

2017-07-09 11:05 UTC, Mori-Atsushi commented on css/top.css
> +
ここの指示内容の確認お願いします。

2017-07-09 11:05 UTC, Mori-Atsushi commented on css/top.css
> +}
消えてません。

2017-07-09 11:05 UTC, Mori-Atsushi commented on index.html
> +      <h1><a href="./"><img src="./images/CyderLogo.png" alt="Cyder" class="title"></a></h1>
logo.pngです。

2017-07-09 11:05 UTC, Mori-Atsushi commented on js/script.js
> +
これの対応お願いします。
2行目に`changeHeaderTranspearent()` を追加すればOKです。

2017-07-09 12:12 UTC, mori-atsushi approved these changes

2017-07-09 12:14 UTC, merged