productのhtmlを作成しました
cyder/cyder-website pull request #35
Opened 2017-05-24 07:00 UTC by rururuuko

#6

Aktivaの画像が分からなかったので、仮画像を入れています。
READ MOREはhrefを使いましたが、合っているでしょうか・・・

2017-05-24 08:21 UTC, mori-atsushi requested changes
いい感じです！いくつかちょっとした問題があるので、修正お願いします。

2017-05-24 08:21 UTC, Mori-Atsushi commented on product/index.html
> +   <div class="content">
スペース間違って消してますよ

2017-05-24 08:21 UTC, Mori-Atsushi commented on product/index.html
> +      </div>
42〜44行目だけでなく、42〜50行目までをまとめて一つの要素で囲いましょうか
ここは`div`より`article`を使ったほうがいいと思います。

2017-05-24 08:21 UTC, Mori-Atsushi commented on product/index.html
> +        <p>Aktiva V2</p>
ここは`p`ではなく見出し2を示す`h2`がいいと思います！

2017-05-24 08:21 UTC, Mori-Atsushi commented on product/index.html
> +        <img src="../images/Aktiva-logo.jpg" alt="aktiva">
上の「Aktiva V2」の代わりに画像を使用するので、`h2`タグで`img`タグを囲ってください

2017-05-24 08:21 UTC, Mori-Atsushi commented on product/index.html
> +        <a href="">READ MORE</a>
まだページがないですが、以下のようにリンクを付けてもらえますか。
```html
<a href="./aktiva.html">READ MORE</a>
```

2017-05-24 08:32 UTC, mori-atsushi requested changes

2017-05-24 08:32 UTC, Mori-Atsushi commented on product/index.html
> +        <img src="../images/Aktiva-logo.jpg" alt="aktiva">
以下のフォルダに`aktiva-logo-white.png'をアップロードしました。お願いします。
https://drive.google.com/drive/u/0/folders/0B5og1PuOXWEBOC1TaVh3WmtjNTQ

2017-05-24 08:32 UTC, Mori-Atsushi commented on product/index.html
> +        <p>coming soon・・・</p>
`coming soon・・・` → `Coming Soon...`

ここは文章でないので `p` は使わず直接 `div` で囲いましょうか
後々cssで指定しやすくするため
```
<div class="coming-soon"></div>
```
みたいに `class` を指定して頂けると幸いです。

2017-05-24 17:08 UTC, rururuuko commented
以下の２点について、コツなどあれば教えてもらいたいです。
（記述が難しければ、ミーティング終わりなどに少し教えてもられば幸いです...！）
- <div>と<article>の違い
  （調べてふんわりとは分かったのですが、具体的な使い分けがイマイチ分かりません）
- Coming soon...のところで<p>ではな<div>を使うところ

お手数をおかけしますが、よろしくお願いします。

2017-05-24 17:29 UTC, Nishihara-Daiki commented
僕の感覚は次の通りです。(僕もよくわかっていない、間違ってたら教えて)
> `<div>` と `<article>` の違い
`<article>` は、記事。難しいので個人的にあまり使わないです。
`<div>` は、明確な意味を持たない箱。他にピッタリのタグが見つからない、CSSでのレイアウト実装の都合など。困ったらこれを使ってしまう・・・が、乱用は良くないんでしょうね・・・

> Coming soon...のところで `<p>` ではなく `<div>` を使うところ
 `<p>` でもいいと思います。森に聞かないとわかりませんが、Coming soon... の箇所は、READ MORE に変わる部分で、それに合わせたんじゃないかなと思います。(今はREAD MORE部分が `<button>` になっていましたっけ？ 確か、少なくとも初稿では `<div>` が使われてたかと)

2017-05-25 00:06 UTC, Mori-Atsushi commented
タグは厳密な使い分けがあるわけではないので、最終的には感覚だと思います…ｗ
また、正解・不正解があるわけでもないので、好き嫌いによるものも大きいです。
以下、僕の見解なので参考までに。

## `article` 、 `section` 、 `div` など
> <section>は一般的なセクションを定義するタグであるため、 要素内容を記事として配信する意味合いが強い場合には、<article>を使用することが推奨されています。 また、 補足情報の場合には<aside>、 ナビゲーションの場合には<nav>を使用します。 他にも、 ヘッダに該当する場合には<header>、 フッタの場合には<footer>、 などのタグを使用するほうが、ウェブページの文書構造がより明確になるでしょう。

http://www.htmq.com/html5/section.shtml

クローラは文章の意味を解析することができないので（最近はだいぶできるようになりましたが…）、`div` よりも `article` や `section` など、意味を持つタグをできるだけ使用することで、ここは〜について書いてますよ。っということを示します。
`article` は記事の内容なので、ここからここまでは一つの記事の内容ですよっという意味を示します。
個人的には、ニュース記事、プロダクト記事等、順番を入れ替えても成り立つコンテンツに対して付与しています。
反対に `section` はこの順番で読まないと意味が伝わらないコンテストに付与しています。例えばトップページはABOUT→NEWS→PRODUCT→CONTACTの順に読んでほしいわけなので、 `section` を使ってます。
もちろん  `NEWS section` の中に `ニュース記事 article` が存在しても構いません。
他のどの要素でも表現できない場合（cssでのデザイン用等）、最終手段として `div` を使います。

## `p` と `div`
西原くんの言うとおりREAD MOREと合わせた節もありますが、 `p` はParagraphの略で段落を示します。
「 Coming Soon...」は段落というより単語に近い使われ方をしているので `p` は不適切だと感じました。
本来は「将来リンクになる場所」というタグを割り当てるべきなのですが、もちろんそんなタグは存在しないので `div` を選択しました。

2017-05-25 00:07 UTC, mori-atsushi requested changes
後もうちょっとです！よろしくお願いします。

2017-05-25 00:07 UTC, Mori-Atsushi commented on product/index.html
> +      <div>
こちら側が `article` になっていません！
上の記事と構造を合わせてもらえますか？

2017-05-25 03:38 UTC, rururuuko commented
西谷くん、森くん、詳しい解説ありがとうございます！
厳密でないので、ググっても分かりにくい解説が多かったんですね。

修正もありがとうございます！

2017-05-25 07:52 UTC, closed without merging