Aktiva特設サイトHTML構造完成
cyder/cyder-website pull request #52
Opened 2017-05-27 14:49 UTC by Nishihara-Daiki

#2

2017-05-27 15:26 UTC, mori-atsushi requested changes

2017-05-27 15:26 UTC, Mori-Atsushi commented on product/aktiva.html
> +        <img src="./images/logo.png" alt="aktiva">
リンク切れ。画像もアップロードしてください。

2017-05-27 15:26 UTC, Mori-Atsushi commented on product/aktiva.html
> +        <div>比類なきダンス体験。</div> <!-- CSS font-size:(#)vw; を想定したが、要相談 -->
font-sizeは固定でいいんじゃないかな？

2017-05-27 15:26 UTC, Mori-Atsushi commented on product/aktiva.html
> +      <p>Aktiva(アクティーバ)は、・・・<br>お手本を・・・</p>
全部書き込んでください。

2017-05-27 15:26 UTC, Mori-Atsushi commented on product/aktiva.html
> +        <hr>
hrじゃなくてafterとかで実装したほうがよさそう？

2017-05-27 15:26 UTC, Mori-Atsushi commented on product/aktiva.html
> +        <div>比類なきダンス体験。</div> <!-- CSS font-size:(#)vw; を想定したが、要相談 -->
ここのdivいるかな？

2017-05-27 15:26 UTC, Mori-Atsushi commented on product/aktiva.html
> +        <img src="">
@ehnh 画像もらえますか。

2017-05-27 15:26 UTC, Mori-Atsushi commented on product/aktiva.html
> +      <div class="copyright">&copy; 2017 <a href="../">Cyder</a></div>
リンク無しで（本体ページと合わせてください。

2017-05-27 15:26 UTC, Mori-Atsushi commented on product/aktiva.html
> +      <div></div>
youtube埋め込みかな…？

2017-05-28 05:29 UTC, Nishihara-Daiki commented on product/aktiva.html
> +        <div>比類なきダンス体験。</div> <!-- CSS font-size:(#)vw; を想定したが、要相談 -->
横線の長さを、テキストに合わせるなら、font-size が連続的に変わってほしい

2017-05-28 05:31 UTC, Mori-Atsushi commented on product/aktiva.html
> +        <div>比類なきダンス体験。</div> <!-- CSS font-size:(#)vw; を想定したが、要相談 -->
線の長さだけ変えたらあかんのかな？
font-sizeって縦の長さの指定で、横の長さはフォントの種類によって左右されるからあんまり意味ない気がする

2017-05-28 05:33 UTC, Nishihara-Daiki commented on product/aktiva.html
> +        <div>比類なきダンス体験。</div> <!-- CSS font-size:(#)vw; を想定したが、要相談 -->
そうか、横幅が指定できないのか
線の長さを離散的に変化させる？

2017-05-28 05:37 UTC, Mori-Atsushi commented on product/aktiva.html
> +        <div>比類なきダンス体験。</div> <!-- CSS font-size:(#)vw; を想定したが、要相談 -->
線は長めに作ってはみ出させればいいかなと思ってた

2017-05-28 05:43 UTC, Nishihara-Daiki commented on product/aktiva.html
> +        <div>比類なきダンス体験。</div> <!-- CSS font-size:(#)vw; を想定したが、要相談 -->
画面の端はそれでいいけど、テキスト側に被らないようにするにはどうするのがベスト？
テキストを左右中央寄せにしたいから、 `<h2> ::before <div> Title text </div> </h2>` で、 ::before だけ浮かせて、 `<div></div>` をセンタリングしたい

2017-05-28 05:46 UTC, Mori-Atsushi commented on product/aktiva.html
> +        <div>比類なきダンス体験。</div> <!-- CSS font-size:(#)vw; を想定したが、要相談 -->
どうしよ？ワカンネ

2017-05-28 05:48 UTC, Mori-Atsushi commented on product/aktiva.html
> +        <div>比類なきダンス体験。</div> <!-- CSS font-size:(#)vw; を想定したが、要相談 -->
divは別にいらなくて、h2をセンタリング、h2のアフターをabsoluteでいけねーかな？

2017-05-28 05:48 UTC, Nishihara-Daiki commented on product/aktiva.html
> +        <div>比類なきダンス体験。</div> <!-- CSS font-size:(#)vw; を想定したが、要相談 -->
それで、フォントサイズを細かく変えるしかないと思ったけど、横幅は指定しにくいの考えてなかった

2017-05-28 07:37 UTC, Nishihara-Daiki commented on product/aktiva.html
> +        <div>比類なきダンス体験。</div> <!-- CSS font-size:(#)vw; を想定したが、要相談 -->
> divは別にいらなくて、h2をセンタリング、h2のアフターをabsoluteでいけねーかな？
じゃあ、とりあえず `<div>` 無しにして、CSS作成の時に考えましょ

2017-05-28 07:39 UTC, Nishihara-Daiki commented on product/aktiva.html
> +      <div></div>
Youtube 埋め込みですね

2017-05-28 07:52 UTC, Nishihara-Daiki commented on product/aktiva.html
> +        <img src="./images/logo.png" alt="aktiva">
:one:  特設サイトの画像も /images/ に入れますか？
:two:  新しいディレクトリ /product/images/ を作りますか？
:three: ディレクトリを作らず、HTMLと同じ階層 /product/ に入れますか？

2017-05-28 08:49 UTC, Nishihara-Daiki commented on product/aktiva.html
> +        <img src="./images/logo.png" alt="aktiva">
あ、画像isどこ

2017-05-28 09:02 UTC, Mori-Atsushi commented
画像ここにない？（MEMO欄
https://github.com/cyder-akashi/cyder-website/projects/2

2017-05-28 12:01 UTC, Mori-Atsushi commented on product/aktiva.html
> +      <div></div>
ここで頼む
https://youtu.be/IhZAtxQeH2k

2017-05-29 00:39 UTC, Nishihara-Daiki commented on product/aktiva.html
> +      <div></div>
> この動画は限定公開です。本当に共有してもよろしいですか？

よろしいですか？

2017-05-29 00:43 UTC, Mori-Atsushi commented on product/aktiva.html
> +      <div></div>
よろしいです（既に共有されてる

2017-05-29 03:23 UTC, mori-atsushi requested changes
一つだけ修正お願いします！

2017-05-29 03:23 UTC, Mori-Atsushi commented on product/aktiva.html
>          <hr>
こっちの `hr` 消し忘れてる

2017-05-29 06:15 UTC, mori-atsushi approved these changes
お疲れ様でした。マージしましょう。
`merge pull request` ではなく `squash and merge` を使ってマージしてください。（マージボタンの左のメニューから選択できます。）

2017-05-29 06:54 UTC, Mori-Atsushi commented
マージの際、タイトルはそのまま、コメントは編集事項がわかるよう最小限にまとめてください。
レビューによる修正とかは不要です。

2017-05-29 10:02 UTC, merged