favicon追加
cyder/cyder-website pull request #55
Opened 2017-05-28 10:20 UTC by Nishihara-Daiki

#44 pngでfaviconを追加した

2017-05-28 11:10 UTC, mori-atsushi requested changes
favicon画像背景透過されてないね
あと、aktiva特設サイトも一緒に指定したいので一旦保留で

2017-05-29 10:06 UTC, Mori-Atsushi commented
PRとIssueで２重にプロジェクト登録するとわけわからなくなるので、PRの方は登録しない方針で行こうと思います。

2017-05-29 10:08 UTC, Mori-Atsushi commented
developmentブランチをrebaseして作業再開お願いします。
```console
git checkout 44-favicon
git rebase development
```

2017-05-29 11:01 UTC, Nishihara-Daiki commented
> PRとIssueで２重にプロジェクト登録するとわけわからなくなるので、PRの方は登録しない方針で行こうと思います。

What do u mean

2017-05-29 11:03 UTC, Mori-Atsushi commented
PRを作成するときは、右カラムの
* Reviewers
* Assignees（自分）
* Labels
だけ指定してくれたらあとは指定しなくていいよ。の意味

2017-05-29 11:04 UTC, Nishihara-Daiki commented
何か余計に指定していたということか

2017-05-30 17:18 UTC, Nishihara-Daiki commented
Aktiva特設サイトの場所がわからなくて困ってる
```$ git checkout 44-favicon
$ git rebase development```

2017-06-01 01:37 UTC, Nishihara-Daiki commented
ファビコンつきました

2017-06-01 01:40 UTC, Mori-Atsushi commented
背景透過版もください。

2017-06-01 07:17 UTC, Nishihara-Daiki commented
faviconの背景色を透明に変更しました

2017-06-01 09:23 UTC, mori-atsushi approved these changes
僕は透明のほうが好きです。

2017-06-01 09:23 UTC, Mori-Atsushi commented on contact/index.html
> +    <link rel="icon" type="../image/png" href="images/favicon.png">
リンク間違い

2017-06-01 13:47 UTC, Nishihara-Daiki commented
修正しました

2017-06-01 15:04 UTC, Mori-Atsushi commented
Squash and mergeボタンを押してマージしてください。
コメントは適度に編集して頂けると。

2017-06-02 01:23 UTC, Nishihara-Daiki commented
> コメントは適度に編集して頂けると。

どう言う意味？

2017-06-02 01:24 UTC, merged