news詳細のhtmlファイルを作成（Imaginecupのみ）
cyder/cyder-website pull request #68
Opened 2017-05-31 04:34 UTC by rururuuko

#8 ひとまず、imaginecupのみ作成しました。（他は構造同じだと思うので）
　  ご確認お願いします。

2017-05-31 04:42 UTC, rururuuko commented
画像指定場所が間違っていました。今から修正します。

2017-05-31 06:14 UTC, mori-atsushi requested changes
だいたいいいと思います！
`cyder-website` という変なものがaddされてるので確認お願いします。

2017-05-31 06:14 UTC, Mori-Atsushi commented on news/imaginecup170322.html
> +        <p>2017.3.22</p>
`p` タグではなく `time` タグを使用しましょう。

2017-05-31 06:14 UTC, Mori-Atsushi commented on news/imaginecup170322.html
> +        <div>Imagine Cup 2017</div>
これはリンクなので `div` タグではなく `a` タグを使用しましょう。
リンク先は https://www.microsoft.com/ja-jp/education/imagine-cup.aspx でお願いします。

2017-05-31 06:14 UTC, Mori-Atsushi commented on news/imaginecup170322.html
> +        <img src="../images/imagine-cup-2017.png" alt="imagine-cup-2017">
```
./images/news/
```
のフォルダ内にあります。

2017-05-31 08:43 UTC, rururuuko commented
確認ありがとうございました。
修正しました！

2017-05-31 08:44 UTC, Mori-Atsushi commented
このコミットはなんでしょう…？
```
Merge https://github.com/cyder-akashi/cyder-website into 8-news-html
```

2017-05-31 09:06 UTC, Mori-Atsushi commented
```console
git revert -m 1 b02d03a18002da6c8b33c65acc6f64b5856f25df
git reset --mixed 4a78ae7f2031ea49c08561ed975294db2dda0b47
git add --all
git commit -m "news詳細のhtmlファイルを修正"
git push -f origin 8-news-html
```
これで戻るはずです。

2017-05-31 09:14 UTC, mori-atsushi requested changes
先にブランチの修正をしてから、こちらもお願いします。

2017-05-31 09:14 UTC, Mori-Atsushi commented on news/procon161025.html
> +        <img src="../images/news/procon161025.jpg" alt="procon">
ここは以下のページへのリンクを付けてもらってもいいですか？
```html
<a target="_blank" href="http://www.procon.gr.jp/?page_id=59141">第27回全国高等専門学校プログラミングコンテスト</a>
```

2017-05-31 09:14 UTC, Mori-Atsushi commented on news/imaginecup170322.html
> +        <a href=" https://www.microsoft.com/ja-jp/education/imagine-cup.aspx ">Imagine Cup 2017</a>
すみません！忘れてました！
リンクを新しいタブで開きたいので、以下のように `target="_blank"` を指定してもらってもいいですか？
他のページも同様です。
```html
<a target="_blank" href="https://www.microsoft.com/ja-jp/education/imagine-cup.aspx">Imagine Cup 2017</a>
```

2017-05-31 09:14 UTC, Mori-Atsushi commented on news/akashitv161117.html
> +        <img src="../images/news/akashitv161117.jpg" alt="akashitv">
ここは画像埋め込みじゃなく、動画埋め込みにしちゃいましょうか。
上のaタグもいりません。

```html
<iframe width="560" height="315" src="https://www.youtube.com/embed/fWG-fiZGLaI?ecver=1" frameborder="0" allowfullscreen></iframe>
<iframe width="560" height="315" src="https://www.youtube.com/embed/qpZMa-8J-MQ?ecver=1" frameborder="0" allowfullscreen></iframe>
```

2017-05-31 09:14 UTC, Mori-Atsushi commented on news/imaginecup170322.html
> +        <a href=" https://www.microsoft.com/ja-jp/education/imagine-cup.aspx ">Imagine Cup 2017</a>
URLの前後にスペースは必要ありません。

2017-05-31 12:16 UTC, Ruriko0120 commented
何から何までありがとうございます！
修正します！

2017-06-01 10:24 UTC, rururuuko commented
ご指摘内容、修正しました！

2017-06-01 10:31 UTC, mori-atsushi requested changes
newsの画像がないからマージされたんですね。
そういう場合はマージではなくrebaseを使います。
以下のコマンドを実行してみてください。
```console
git checkout development
git pull origin development
git checkout 8-news-html
git rebase development
git push -f origin 8-news-html
```

もうちょっとです！よろしくお願いします！

2017-06-01 10:31 UTC, Mori-Atsushi commented on news/akashitv161117.html
>          <img src="../images/news/akashitv161117.jpg" alt="akashitv">
pを消さないでください！！！

2017-06-01 10:31 UTC, Mori-Atsushi commented on news/akashitv161117.html
>          <img src="../images/news/akashitv161117.jpg" alt="akashitv">
申し訳ないのですが、動画があるのでimgタグの部分は消しちゃいましょうか。

2017-06-01 10:32 UTC, mori-atsushi requested changes

2017-06-01 10:32 UTC, Mori-Atsushi commented on news/procon161025.html
> +        <a target="_blank" href="http://www.procon.gr.jp/?page_id=59141">第27回全国高等専門学校プログラミングコンテスト 課題部門に参加しました。 「舞鏡(まいかがみ)－世界初ダンス用ARスマートミラー－」というタイトルで発表し、特別賞、DMM.comラボ企業賞、NICT賞の3件の賞を受賞しました。</a>
ここもpを消さないでください！

2017-06-01 10:40 UTC, mori-atsushi requested changes
本当に申し訳ございません…

2017-06-01 10:40 UTC, Mori-Atsushi commented on news/akashitv161117.html
> +       <article>
ここで重大なミスを発見しました…
インデントはスペース1つではなく2つです…
全てのファイル、全ての部分で間違っているので修正お願いします…
今後はtabキーを使うように心がけてみてください…

2017-06-01 11:02 UTC, Mori-Atsushi commented on news/akashitv161117.html
> +       <article>
よく見たらakashitv1611117.html のarticleのインデントが間違ってるだけですね。
ここだけ直してください。
お騒がせしました。

2017-06-01 11:53 UTC, rururuuko commented on news/akashitv161117.html
> +       <article>
あ・・・たぶんそれ、学校でやったんですがeditorconfig入ってなかったかもです；
ありがとうございます。

2017-06-02 03:23 UTC, mori-atsushi requested changes
いろいろ伝わってない部分があったみたいですね…
二度手間なので、わかりにくい部分があったら遠慮なく聞いてください…

2017-06-02 03:23 UTC, Mori-Atsushi commented on news/akashitv161117.html
> +        <p><iframe width="560" height="315" src="https://www.youtube.com/embed/fWG-fiZGLaI?ecver=1" frameborder="0" allowfullscreen>「ケーブルNEWSあかし」明石高専が特別賞を受賞！</iframe></p>
ifrmeをpで囲わないでください（泣）
```html
<p>2017年3月8日にコクヨホールで開催された平成28年度起業家甲子園に参加しました。Aktivaの発表を行い、審査員特別賞の他、 ABCドリームベンチャーズ企業様からABC賞、さくらインターネット株式会社からさくらインターネット賞を頂きました。</p>
```
が消されてるので戻してくださいという意味です。

2017-06-02 03:23 UTC, Mori-Atsushi commented on news/procon161025.html
> +        <p><a target="_blank" href="http://www.procon.gr.jp/?page_id=59141">第27回全国高等専門学校プログラミングコンテスト</a>課題部門に参加しました。 「舞鏡(まいかがみ)－世界初ダンス用ARスマートミラー－」というタイトルで発表し、特別賞、DMM.comラボ企業賞、NICT賞の3件の賞を受賞しました。</P>
Imagine Cup等のページと同じく、第27回全国高等専門学校プログラミングコンテストのリンクはpの後にお願いします。
p内のaタグはいりません。

2017-06-04 14:31 UTC, mori-atsushi approved these changes
お疲れ様でした！マージしましょう。
マージは、squashではなく、デフォルトのmerge pull requestを使用してください。
コミットメッセージを修正したり、複数コミットを一つにまとめたい場合は `rebase -i ` を用いて修正し、フォースプッシュを使って下さい。
分からなければ聞いてもらって大丈夫です！

2017-06-05 05:58 UTC, merged